sonata_admin:
    title: 'SGESOP'
    title_logo: "./img/logo.png"
    security:
        handler: sonata.admin.security.handler.role
    dashboard:
        groups:
            sonata.admin.group.administration:
                label:           sonata_administration
                label_catalogue: SonataAdminBundle
                icon: '<i class="glyphicon glyphicon-user"></i>'
                items:
                    - sonata.user.admin.user
                    - sonata.user.admin.group
                    - sonata.user.admin.office
                    - sonata.admin.app.clasificador
                    - sonata.admin.app.producto
                    - sonata.admin.app.trabajador
            sonata.admin.group.content:
                label:           sonata_media
                label_catalogue: SonataMediaBundle
                icon:            '<i class="fa fa-image"></i>'
                items:
                    - sonata.media.admin.media
                    - sonata.media.admin.gallery

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
