sonata_admin:
    title: 'SGESOP'
    title_logo: "./img/logo.png"
    dashboard:
        groups:
            sonata.admin.group.administration:
                label:           sonata_administration
                label_catalogue: SonataAdminBundle
                icon: '<i class="glyphicon glyphicon-user"></i>'
                items:
                    - sonata.user.admin.user
                    - sonata.user.admin.group
                    - sonata.user.admin.office

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
