sonata_admin:
    title: 'SGESOP'
    title_logo: "./img/logo.png"
    security:
        handler: sonata.admin.security.handler.role
    dashboard:
        groups:
            sonata.admin.group.administration:
                label: 'Seguridad'
                icon: '<i class="glyphicon glyphicon-user"></i>'
                items:
                    - sonata.user.admin.user
                    - sonata.user.admin.group
                    - app_auditoria.admin.auditoria_log
#            sonata.admin.group.content:
#                label:           sonata_media
#                label_catalogue: SonataMediaBundle
#                icon:            '<i class="fa fa-image"></i>'
#                items:
#                    - sonata.media.admin.media
#                    - sonata.media.admin.gallery
            sonata.admin.empresa:
                icon:  '<i class="fa fa-gears"></i>'
                label: 'Empresa'
                items:
                    - sonata.user.admin.office
                    - sonata.admin.app.clasificador
                    - sonata.admin.app.trabajador

            sonata.admin.nomenclador:
                label_catalogue: app
                icon:  '<i class="fa fa-gears"></i>'
                items:
                    - sonata.admin.nomenclador.add
                    - sonata.admin.nomenclador.agudeza_visual
                    - sonata.admin.nomenclador.dp
                    - sonata.admin.nomenclador.eje
                    - sonata.admin.nomenclador.color

            sonata.admin.producto_optica:
                label_catalogue: app
                icon:  '<i class="fa fa-gears"></i>'
                items:
#                    - sonata.admin.app.producto
                    - sonata.admin.nomenclador.accesorio
                    - sonata.admin.nomenclador.armadura
                    - sonata.admin.nomenclador.cristal
                    - sonata.admin.nomenclador.tinte_cristal
                    - sonata.admin.nomenclador.lupa

            sonata.admin.dpto_economia:
                label: "Dpto. Economía"
                items:
                    - app.informe_recepcion_economico
#                    - route: admin_app_movimientoalmacen_alamacen_lista_factura
#                      label: Informe de Recepción
#                      roles: ['ROLE_ADMIN']

            sonata.admin.dpto_comercial:
                label: "Dpto. Comercial"
                items:
                    - app.informe_recepcion_optica

            sonata.admin.almacen:
                label_catalogue: app
                icon:  '<i class="fa fa-folder"></i>'
                items:
#                    - sonata.admin.mv.factura
#                    - sonata.admin.app.movimiento_almacen
                    - app.almacen
                    - app.despacho_almacen

            sonata.admin.optometrista:
                label: 'Optometrista'
                icon:  '<i class="fa fa-folder"></i>'
                items:
                    - sonata.admin.app.paciente
#                    - sonata.admin.app.receta

            servicios_ordenes:
                label: Ventas
                label_catalogue: AppBundle
                icon: '<i class="fa fa-money"></i>'
                roles: [ ROLE_USER ]
                items:
#                    - sonata.admin.app.receta
#                    - sonata.admin.app.orden_corte_montaje
                    - sonata.admin.app.orden_servicio
            taller_tallado:
                label: Taller de Tallado
                items:
                    - sonata.admin.app.solicitud_tallado
    options:
        html5_validate:  true     # enable or disable html5 form validation
        confirm_exit:    true     # enable or disable a confirmation before navigating away
        js_debug:        false    # enable or disable to show javascript debug messages
        use_select2:     true     # enable or disable usage of the Select2 jQuery library
        use_icheck:      true     # enable or disable usage of the iCheck library
        use_bootlint:    false    # enable or disable usage of Bootlint
        use_stickyforms: true     # enable or disable the floating buttons
        form_type:       standard # can also be 'horizontal'

    templates:
        layout:             '::Admin/layout.html.twig'
        user_block:         '::Admin/Core/user_block.html.twig'
        base_list_field:    '::Admin/CRUD/base_list_field.html.twig'

    global_search:
        empty_boxes: hide
    assets:
        # stylesheet paths to add to the page in addition to the list above
        extra_stylesheets:
            - css/app.css

          # javascript paths to add to the page in addition to the list above
        extra_javascripts:
            - js/jquery.validate.js
            - js/additional-methods.js
            - js/app.js
sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.admin.block.search_result:
            contexts: [admin]
