services:
    sonata.admin.nomenclador.armadura:
        class: App\Admin\AppArmaduraAdmin
        arguments: [~, App\Entity\AppArmadura, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: nomenclador.armaduras }
        calls:
            - [ setTranslationDomain, ["NomencladorBundle"] ]
            - [ setTemplate, ['edit', '::Admin/producto/edit.html.twig']]
    sonata.admin.nomenclador.accesorio:
        class: App\Admin\AppAccesorioAdmin
        arguments: [~, App\Entity\AppAccesorio, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: nomenclador.accesorios }
        calls:
            - [ setTranslationDomain, ["NomencladorBundle"] ]
            - [ setTemplate, ['edit', '::Admin/producto/edit.html.twig']]
    sonata.admin.nomenclador.cristal:
        class: App\Admin\AppCristalAdmin
        arguments: [~, App\Entity\AppCristal, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: nomenclador.cristales }
        calls:
            - [ setTranslationDomain, ["NomencladorBundle"] ]
            - [ setTemplate, ['edit', '::Admin/producto/edit.html.twig']]
    sonata.admin.nomenclador.tinte_cristal:
        class: App\Admin\AppTinteCristalAdmin
        arguments: [~, App\Entity\AppTinteCristal, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: nomenclador.tinte_cristales }
        calls:
            - [ setTranslationDomain, ["NomencladorBundle"] ]
            - [ setTemplate, ['edit', '::Admin/producto/edit.html.twig']]