services:
    sonata.admin.nomenclador.armadura:
        class: App\Admin\AppArmaduraAdmin
        arguments: [~, App\Entity\AppArmadura, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: nomenclador.armaduras }
        calls:
            - [ setTranslationDomain, ["NomencladorBundle"] ]
            - [ setTemplate, ['edit', '::Admin/producto/edit.html.twig']]
    sonata.admin.nomenclador.accesorio:
        class: App\Admin\AppAccesorioAdmin
        arguments: [~, App\Entity\AppAccesorio, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: nomenclador.accesorios }
        calls:
            - [ setTranslationDomain, ["NomencladorBundle"] ]
            - [ setTemplate, ['edit', '::Admin/producto/edit.html.twig']]
    sonata.admin.nomenclador.cristal:
        class: App\Admin\AppCristalAdmin
        arguments: [~, App\Entity\AppCristal, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: nomenclador.cristales }
        calls:
            - [ setTranslationDomain, ["NomencladorBundle"] ]
            - [ setTemplate, ['edit', '::Admin/producto/edit.html.twig']]
    sonata.admin.nomenclador.tinte_cristal:
        class: App\Admin\AppTinteCristalAdmin
        arguments: [~, App\Entity\AppTinteCristal, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: nomenclador.tinte_cristales }
        calls:
            - [ setTranslationDomain, ["NomencladorBundle"] ]
            - [ setTemplate, ['edit', '::Admin/producto/edit.html.twig']]
    sonata.admin.nomenclador.lupa:
        class: App\Admin\AppLupaAdmin
        arguments: [~, App\Entity\AppLupa, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: nomenclador.lupa }
        calls:
            - [ setTranslationDomain, ["NomencladorBundle"] ]
            - [ setTemplate, ['edit', '::Admin/producto/edit.html.twig']]

    sonata.admin.nomenclador.add:
        class: App\Admin\Nomenclador\AddAdmin
        arguments: [~, App\Entity\Nomenclador\NcAdd, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: nomenclador.add }
        calls:
            - [ setTranslationDomain, ["NomencladorBundle"] ]
    sonata.admin.nomenclador.agudeza_visual:
        class: App\Admin\Nomenclador\AgudezaVisualAdmin
        arguments: [~, App\Entity\Nomenclador\NcAgudezaVisual, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: nomenclador.agudeza_visual }
        calls:
            - [ setTranslationDomain, ["NomencladorBundle"] ]
    sonata.admin.nomenclador.dp:
        class: App\Admin\Nomenclador\DpAdmin
        arguments: [~, App\Entity\Nomenclador\NcDp, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: nomenclador.dp }
        calls:
            - [ setTranslationDomain, ["NomencladorBundle"] ]
    sonata.admin.nomenclador.eje:
        class: App\Admin\Nomenclador\EjeAdmin
        arguments: [~, App\Entity\Nomenclador\NcEje, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: nomenclador.eje }
        calls:
            - [ setTranslationDomain, ["NomencladorBundle"] ]